### ISSUE TITLE
Update README to reflect the latest changes

### ISSUE THREAD

**Issue by zhangl64** [miranska/restore#12]
@miranska, sorry, I just realized that we didn't update the README file to reflect the latest changes, e.g., new output file names, etc.

**Comment by miranska** [comment]
@zhangl64 , looking at the readme, it seems that the inputs are also incorrect. For example, I do not see any `csv` files in `inst/extdata/`. Could you please update `Running the tests` section for the hierarchical case, based on your latest demo? I can then add the flat hierarchy case.

**Comment by miranska** [comment]
Working on it in #14.

**Comment by zhangl64** [comment]
Closed by pull request #14
