### ISSUE TITLE
Add test results of "variable attributes comparison" and "discarded variables" in output data.frame. 

### ISSUE THREAD

**Issue by zhangl64** [miranska/restore#5]
We need to make sure that the output data.frame contains the same data with the output report.

**Comment by zhangl64** [comment]
@miranska resolved by e360f4ae55e9218a11ffc283455945f3c908b7d9
Please review. Thanks.

**Comment by miranska** [comment]
Let's add `count_of_columns_missing_in_old_dataset` and `count_of_columns_missing_in_new_dataset` variables to `hm` for completeness:
https://github.com/miranska/restore/blob/e360f4ae55e9218a11ffc283455945f3c908b7d9/R/produce_reports.R#L81-L84

Technically, they are derived from the data already present in `hm`, but it may save someone a bit of time ;-)

**Comment by zhangl64** [comment]
@miranska , resolved, these two variables are added in 55ae7c14c78e382eb5e97aa2c8ad27c7733cddb8
Please review. Thanks.

**Comment by miranska** [comment]
Reviewed and refactored as per #7
